# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

use_frameworks!

#pod 'Acclaim'
pod 'Acclaim', :path => '~/Library/Mobile Documents/com~apple~CloudDocs/iCloud Drive/Work/Offsky/Acclaim'