# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

use_frameworks!

pod 'Acclaim', :git => 'https://github.com/gradyzhuo/Acclaim.git'
pod 'TWMLMatrix', :git => 'https://github.com/gradyzhuo/TWMLMatrix.git'
